### ISSUE TITLE
question about experimental results.

### ISSUE THREAD

**Issue by Jason-cpp** [megvii-research/SOLQ#1]
### 1
The dataset in the caption of  Table1 is 'coco test-dev'.
The dataset in the caption of  Table2 is 'coco val'.
But the results are the same for 'SOLQ(r50)' in Table1  and 'D-DETR∗+UQR(r50)' in Table2. Is this a mistake?

### 2

What is the setting of the experiments in Table3?  Experiments use 1x(12ep) training strategy?
.

**Comment by vaesl** [comment]
> ### 1
> 
> The dataset in the caption of Table1 is 'coco test-dev'.
> The dataset in the caption of Table2 is 'coco val'.
> But the results are the same for 'SOLQ(r50)' in Table1 and 'D-DETR∗+UQR(r50)' in Table2. Is this a mistake?
> ### 2
> 
> What is the setting of the experiments in Table3? Experiments use 1x(12ep) training strategy?
> .

Thanks for your pointing out this mistake. The result of 'D-DETR∗+UQR(r50)' in Tab.2 is wrongly reported by the test-dev dataset and the 'D-DETR∗+UQR(r101)' is correct. The 'D-DETR∗+UQR(r50)' on val set should be 40.1mAP as shown in the following text. We will update the result ASAP on the arxiv. Note that the performance gap between the r50 and r101 is not that large on val set while performance gap on test-dev set is about 1.2%.

IoU metric: segm				
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.401				
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.631				
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.431				
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.208				
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.437				
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.594				
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.324				
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.520				
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.550				
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.344				
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.598				
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.729				
IoU metric: bbox				
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.485		
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.662		
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.528		
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.301			
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.516	
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.647	
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.376	
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.619	
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.661	
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.451	
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.710
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.840						`

As for the experiment setting in Tab.3, we also adopt 50 epoches for training except that only the single feature
level with C5 is used.

**Comment by vaesl** [comment]
> ### 1
> 
> The dataset in the caption of Table1 is 'coco test-dev'.
> The dataset in the caption of Table2 is 'coco val'.
> But the results are the same for 'SOLQ(r50)' in Table1 and 'D-DETR∗+UQR(r50)' in Table2. Is this a mistake?
> ### 2
> 
> What is the setting of the experiments in Table3? Experiments use 1x(12ep) training strategy?
> .

Thanks for your pointing out this mistake. Please refer to the latest version of SOLQ tomorrow. As for the experiment setting in Tab.3, we also adopt 50 epoches for training except that only the single feature level with C5 is used.
