### ISSUE TITLE
Baseline instance segmentation results with D-DETR

### ISSUE THREAD

**Issue by vadimkantorov** [megvii-research/SOLQ#10]
I found that you provide [DeformableDETRsegm](https://github.com/megvii-research/SOLQ/blob/main/models/segmentation.py#L75) class.

Does it correspond to `D-DETR∗+SQR` baseline in Table2?

Thank you!

**Comment by vadimkantorov** [comment]
I'm basically looking for baselines of Deformable-DETR with a simple segmentation head.

Can I use for that DeformableDETR (models/deformable_detr.py) along with DeformableDETRsegm (models/segmentation.py)?

Do you have some segmentation results for this baseline?

Thanks!

**Comment by vadimkantorov** [comment]
This is at epoch50, right? Do you by chance have any learning curves?

**Comment by vadimkantorov** [comment]
DDETR*-SQR doesn't do any DCT / PCA / other mask compression, right?

**Comment by dbofseuofhust** [comment]
> DDETR*-SQR doesn't do any DCT / PCA / other mask compression, right?

yes, there are no mask compression in SQR.

**Comment by vadimkantorov** [comment]
Unfortunately the log doesn't contain the AP values :( But it's still useful. Thank you!

**Comment by dbofseuofhust** [comment]
> Unfortunately the log doesn't contain the AP values :( But it's still useful. Thank you!

AP values?, it appears in the end of each line as 'test_coco_eval_box' and ' 'test_coco_eval_mask':
![image](https://user-images.githubusercontent.com/31989795/136950159-aa4d9b22-8604-4a87-8757-c5f28e3e81cd.png)

does is your need?

**Comment by vadimkantorov** [comment]
Ah, great, these numbers correspond to the following, right?
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = ...
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = ...
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = ...
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = ...
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = ...
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = ...
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = ...
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = ...
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = ...
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = ...
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = ...
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = ...
```

**Comment by dbofseuofhust** [comment]
> Ah, great, these numbers correspond to:
> 
> ```
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = ...
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = ...
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = ...
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = ...
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = ...
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = ...
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = ...
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = ...
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = ...
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = ...
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = ...
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = ...
> ```

yes, your are right.

**Comment by vadimkantorov** [comment]
Thank you!
