### ISSUE TITLE
Difference between feature usage between DeformableDETR and DeformableDETRsegm

### ISSUE THREAD

**Issue by vadimkantorov** [megvii-research/SOLQ#14]
Could you please comment on difference between feature usage in DeformableDETR and DeformableDETRsegm?

The first uses all `features` elements, and the latter only `features[-1]`...

Thank you!

https://github.com/megvii-research/SOLQ/blob/5471f58/models/deformable_detr.py#L136-L162 :
```python
        features, pos = self.backbone(samples)

        srcs = []
        masks = []
        for l, feat in enumerate(features):
            src, mask = feat.decompose()
            srcs.append(self.input_proj[l](src))
            masks.append(mask)
            assert mask is not None
        if self.num_feature_levels > len(srcs):
            _len_srcs = len(srcs)
            for l in range(_len_srcs, self.num_feature_levels):
                if l == _len_srcs:
                    src = self.input_proj[l](features[-1].tensors)
                else:
                    src = self.input_proj[l](srcs[-1])
                m = samples.mask
                mask = F.interpolate(m[None].float(), size=src.shape[-2:]).to(torch.bool)[0]
                pos_l = self.backbone[1](NestedTensor(src, mask)).to(src.dtype)
                srcs.append(src)
                masks.append(mask)
                pos.append(pos_l)

        query_embeds = None
        if not self.two_stage:
            query_embeds = self.query_embed.weight
        hs, init_reference, inter_references, enc_outputs_class, enc_outputs_coord_unact, _, _ = self.transformer(srcs, masks, pos, query_embeds)

```

https://github.com/megvii-research/SOLQ/blob/5471f58/models/segmentation.py#L49-L55 :
```python
        features, pos = self.detr.backbone(samples)

        bs = features[-1].tensors.shape[0]

        src, mask = features[-1].decompose()
        src_proj = self.detr.input_proj(src)
        hs, memory = self.detr.transformer(src_proj, mask, self.detr.query_embed.weight, pos[-1])
```

**Comment by dbofseuofhust** [comment]
> Could you please comment on difference between feature usage in DeformableDETR and DeformableDETRsegm?
> 
> The first uses all `features` elements, and the latter only `features[-1]`...
> 
> Thank you!
> 
> https://github.com/megvii-research/SOLQ/blob/5471f58/models/deformable_detr.py#L136-L162 :
> 
> ```python
>         features, pos = self.backbone(samples)
> 
>         srcs = []
>         masks = []
>         for l, feat in enumerate(features):
>             src, mask = feat.decompose()
>             srcs.append(self.input_proj[l](src))
>             masks.append(mask)
>             assert mask is not None
>         if self.num_feature_levels > len(srcs):
>             _len_srcs = len(srcs)
>             for l in range(_len_srcs, self.num_feature_levels):
>                 if l == _len_srcs:
>                     src = self.input_proj[l](features[-1].tensors)
>                 else:
>                     src = self.input_proj[l](srcs[-1])
>                 m = samples.mask
>                 mask = F.interpolate(m[None].float(), size=src.shape[-2:]).to(torch.bool)[0]
>                 pos_l = self.backbone[1](NestedTensor(src, mask)).to(src.dtype)
>                 srcs.append(src)
>                 masks.append(mask)
>                 pos.append(pos_l)
> 
>         query_embeds = None
>         if not self.two_stage:
>             query_embeds = self.query_embed.weight
>         hs, init_reference, inter_references, enc_outputs_class, enc_outputs_coord_unact, _, _ = self.transformer(srcs, masks, pos, query_embeds)
> ```
> 
> https://github.com/megvii-research/SOLQ/blob/5471f58/models/segmentation.py#L49-L55 :
> 
> ```python
>         features, pos = self.detr.backbone(samples)
> 
>         bs = features[-1].tensors.shape[0]
> 
>         src, mask = features[-1].decompose()
>         src_proj = self.detr.input_proj(src)
>         hs, memory = self.detr.transformer(src_proj, mask, self.detr.query_embed.weight, pos[-1])
> ```

Sorry to reply late. 
Actually, DeformableDETR and DeformableDETRsegm use both multi-level features, you should check [DeformableDETRsegm ](https://github.com/megvii-research/SOLQ/blob/5471f58/models/segmentation.py#L75), rather than [DETRsegm](https://github.com/megvii-research/SOLQ/blob/5471f58/models/segmentation.py#L49-L55). Because [DETRsegm](https://github.com/megvii-research/SOLQ/blob/5471f58/models/segmentation.py#L49-L55) is designed for DETR which uses single-level features and [DeformableDETRsegm ](https://github.com/megvii-research/SOLQ/blob/5471f58/models/segmentation.py#L75) is designed for DeformableDETR which uses multi-level features.

**Comment by vadimkantorov** [comment]
Is the bbox prediction done in exactly same way for DeformableDETRsegm and DeformableDETR? Should I be able to load pretrained DeformableDETR weights and finetune for both detection and segmentation?

**Comment by vaesl** [comment]
Yeah, the bbox prediction is the same for DeformableDETRsegm and DeformableDETR.  In our practice, the DeformableDETRsegm is jointly trained from scratch for both detection and segmentation. Of course, you can load the pretrained DeformableDETR weights and finetune for both detection and segmentation.

**Comment by vadimkantorov** [comment]
Thanks for your answers. Indeed, the code using `self.detr.transformer` seems identical to code using `self.transformer`.
