### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by roar-1128** [megvii-research/SOLQ#15]
“Thanks for your attention on SOLQ! It will take about 1.5 days and 2.0 days to train SOLQ with R50 and R101 backbones, respectively. As for the Swin-Large backbone, it will take nearly four days to train due to the large computation cost.”

Excuse me, do you use 2 GPUs or 8 GPUs for training for 1.5 days? the read me you provided uses 8 GPUs. so I confused

**Comment by vaesl** [comment]
Training SOLQ with R50 takes about 1.5 days using 8 Tesla V100 GPUs of a single machine.
