### ISSUE TITLE
Training Logs for SOLQ (D-DETR + UQR)

### ISSUE THREAD

**Issue by songhwanjun** [megvii-research/SOLQ#16]
Thanks for this nice work! 
Could you provide the training logs for your SOLQ models? 
Currently, I can see only the logs for D-DETR + SQR.

**Comment by dbofseuofhust** [comment]
> Thanks for this nice work! Could you provide the training logs for your SOLQ models? Currently, I can see only the logs for D-DETR + SQR.

Hi~, we disable mask evaluation during training for fast training, so the log.txt consist of only loss and box ap. We can send your log.txt if this meet your need or you can retrain the model again.
