### ISSUE TITLE
Semantics of with_vector 

### ISSUE THREAD

**Issue by vadimkantorov** [megvii-research/SOLQ#17]
1. Do I understand correctly that SOLQ(..., with_vector = False) is equivalent to vanilla DeformableDETR(...)?
2. Why are postprocessors created only in args.eval? https://github.com/megvii-research/SOLQ/blob/b35360390b1d51d375dd9d03c39dbce663e223a7/models/solq.py#L614 The postprocessors should be applied at regular evaluation during training too, right? In fast_solq code only args.masks is checked: https://github.com/megvii-research/SOLQ/blob/b35360390b1d51d375dd9d03c39dbce663e223a7/models/fast_solq.py#L588. What's the motivation for this difference?

Thanks!

**Comment by dbofseuofhust** [comment]
> 1. Do I understand correctly that SOLQ(..., with_vector = False) is equivalent to vanilla DeformableDETR(...)?
> 2. Why are postprocessors created only in args.eval? https://github.com/megvii-research/SOLQ/blob/b35360390b1d51d375dd9d03c39dbce663e223a7/models/solq.py#L614
>     The postprocessors should be applied at regular evaluation during training too, right? In fast_solq code only args.masks is checked: https://github.com/megvii-research/SOLQ/blob/b35360390b1d51d375dd9d03c39dbce663e223a7/models/fast_solq.py#L588
>    . What's the motivation for this difference?
> 
> Thanks!

Hi~,
1. SOLQ(..., with_vector = False) is equivalent to vanilla DeformableDETR(...).
2. postprocessors can also be created during training, we just disable it in training for fast training (solq.py), you can enbale it when using fast_solq.py because it is implemented by torch_dct.

**Comment by vadimkantorov** [comment]
Thank you for your answers!
