### ISSUE TITLE
Some questions about potential further experiments.

### ISSUE THREAD

**Issue by dddzg** [megvii-research/SOLQ#2]
Hi, I am keeping focusing on DETR related work. 
This work is really interesting. 
It can be a good supplement answer to the issue https://github.com/facebookresearch/detr/issues/163.

Here, I am still have some questions:
1. I am surprised that UQR could provide more than 7 points improvement on AP^seg, as shown in Table2. May I ask for the detailed comparision about AP^seg_S,AP^seg_M and AP^seg_L?  I wonder where the main improvement comes from? 
2. As seen in table 1, SOLQ performs best on AP^box_L(much more better than other methods). I am confused that why its performance is not best on  AP^seg_L. Could I regard it as the drawback of the mask compression coding on large objects? I wonder whether SQR could perform well on large objects and UQR performs better on small and medium objects. What's your idea?
3. If my understand correctly, this method can easily apply to panoptic segmentation. May I ask for some results about panoptic segmentation? With this result, we could better analyse the gap between SOLQ and DETR.

**Comment by vaesl** [comment]
> Hi, I am keeping focusing on DETR related work.
> This work is really interesting.
> It can be a good supplement answer to the issue [facebookresearch/detr#163](https://github.com/facebookresearch/detr/issues/163).
> 
> Here, I am still have some questions:
> 
>     1. I am surprised that UQR could provide more than 7 points improvement on AP^seg, as shown in Table2. May I ask for the detailed comparision about AP^seg_S,AP^seg_M and AP^seg_L?  I wonder where the main improvement comes from?
> 
>     2. As seen in table 1, SOLQ performs best on AP^box_L(much more better than other methods). I am confused that why its performance is not best on  AP^seg_L. Could I regard it as the drawback of the mask compression coding on large objects? I wonder whether SQR could perform well on large objects and UQR performs better on small and medium objects. What's your idea?
> 
>     3. If my understand correctly, this method can easily apply to panoptic segmentation. May I ask for some results about panoptic segmentation? With this result, we could better analyse the gap between SOLQ and DETR.

Thanks for your attention on our SOLQ! As for your questions, here is my answer:
1. As mentioned in the paper, our SOLQ performs relatively well on small and medium objects. For the results of R50 in Tab.2, our UQR improves the AP^seg_S,AP^seg_M and AP^seg_L by 8.5%, 7.5%, 2.9% compared to the SQR, respectively. As we analyzed in the introduction, 2D ground-truth binary mask is not suitable for the supervision of query embedding. Also, the supervision for the small objects is not efficient under the spatial dimension.
2. I would support your opinion. The mask compression coding will loss more information on large objects compared to small objects, such as the high-frequency components of boundary region.
3. Our SOLQ can be directly applied to the panoptic segmentation task. However, SOLQ mainly focuses on the instance segmentation currently. Feel free to have a try!

**Comment by dddzg** [comment]
Thanks for your response. I roughly read the code, there are two small problems:
1. As the shell `no_vector_loss_norm` is set to False, so we will calculate `F.l1_loss(src_vectors, target_vectors, reduction='mean')` instead of `.sum() / num_boxes`(default DETR style). What your ideas about it? It seems a little weird.
2. This a version of `fast_solq.py` with torch style DCT. Why we do not use it?

**Comment by vaesl** [comment]
> Thanks for your response. I roughly read the code, there are two small problems:
> 
>     1. As the shell `no_vector_loss_norm` is set to False, so we will calculate `F.l1_loss(src_vectors, target_vectors, reduction='mean')` instead of `.sum() / num_boxes`(default DETR style). What your ideas about it? It seems a little weird.
> 
>     2. This is a version of `fast_solq.py` with torch style DCT. Why we do not use it?

1. If the no_vector_loss_norm is set to True, we observed imbalance between the vector loss and detection loss, which results in nearly 0.2~0.3% performance degrade.
2. The fast_solq.py is the original implementation in torch-dct repo(https://github.com/zh217/torch-dct/). We found huge scale difference between this implementation and our cv2 version. Please kindly refer to the issue (reported in https://github.com/zh217/torch-dct/issues/12) for more details. It will bring about 0.7% performance drop.

**Comment by dddzg** [comment]
Thanks a lot.
