### ISSUE TITLE
Swin-L Train and Test Image Resizing 

### ISSUE THREAD

**Issue by ilovecv** [megvii-research/SOLQ#20]
Hi,

You mentioned: 

> [ Higher performance (Box AP=56.5, Mask AP=46.7) is reported by training with long side 1536 on Swin-L backbone, instead of long side 1333.](url)

May I know the image resizing strategies during training and testing? I found some commented codes for Swin-L, for training https://github.com/megvii-research/SOLQ/blob/main/datasets/coco.py#L135 and for testing https://github.com/megvii-research/SOLQ/blob/main/datasets/coco.py#L158. But for testing the long side is 1333 instead of 1536. Could you please clarify this? Thank you very much!

**Comment by vaesl** [comment]
> Hi,
> 
> You mentioned:
> 
> > [ Higher performance (Box AP=56.5, Mask AP=46.7) is reported by training with long side 1536 on Swin-L backbone, instead of long side 1333.](url)
> 
> May I know the image resizing strategies during training and testing? I found some commented codes for Swin-L, for training https://github.com/megvii-research/SOLQ/blob/main/datasets/coco.py#L135 and for testing https://github.com/megvii-research/SOLQ/blob/main/datasets/coco.py#L158. But for testing the long side is 1333 instead of 1536. Could you please clarify this? Thank you very much!

Sorry for the late reply. We have not updated the scale settings for Swin-L backbone. For training, the scale range is set to
scales = [416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1200] and the max_size is set to 1536. For testing, the scale is set to T.RandomResize([1200], max_size=1536).

**Comment by ilovecv** [comment]
thanks
