### ISSUE TITLE
Performance on DETR

### ISSUE THREAD

**Issue by YuqingWang1029** [megvii-research/SOLQ#21]
As the SOLQ is built on D-DETR, have you performed the experiment on the original DETR model? I would be very grateful if you can provide the results.

**Comment by vaesl** [comment]
> 

Hi, thanks for your interest on our SOLQ. We only performed the experiment on the D-DETR due to its fast convergence. Feel free to have a try on original DETR.

**Comment by YuqingWang1029** [comment]
OK, thanks for your reply.
