### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by lxtGH** [megvii-research/SOLQ#5]
Cool work!!!!
Thanks for opensourcing the code.
I wonder how long it takes for training via one machine ?

**Comment by lxtGH** [comment]
Also, what about using swin backbone?

**Comment by vaesl** [comment]
> Cool work!!!!
> Thanks for opensourcing the code.
> I wonder how long it takes for training via one machine ?

Thanks for your attention on SOLQ! It will take about 1.5 days and 2.0 days to train SOLQ with R50 and R101 backbones, respectively. As for the Swin-Large backbone, it will take nearly four days to train due to the large computation cost.

**Comment by lxtGH** [comment]
Thanks for your reply!!

**Comment by lxtGH** [comment]
What is

**Comment by vaesl** [comment]
> Hi! @vaesl What is the batch size per GPU for training Swin or ResNet101 ?

Hi, the batch size of both Swin and ResNet101 are 32 in total. For ResNet101 backbone, the batch size per GPU is 4 on a single V100 machine while for the Swin backbone, the batch size per GPU is 2 on a two V100 machines.

**Comment by lxtGH** [comment]
Hi! When I run the ResNet101 backbone using V100 32GB. I meet out of memory issue. Did you meet this problems? @vaesl

**Comment by vaesl** [comment]
Sorry for the mistake! The experiment of SOLQ with ResNet101 is also conducted on two V100 machines. You can simply modify the dimension of object query from 384 to 256, which can be trained on a single V100 machine while introducing ~0.5 mAP performance drop. We will update the readme file as well as the description in the arxiv paper. Thanks a lot!

**Comment by lxtGH** [comment]
Thanks again~.

**Comment by roar-1128** [comment]
> > Cool work!!!! Thanks for opensourcing the code. I wonder how long it takes for training via one machine ?
> 
> Thanks for your attention on SOLQ! It will take about 1.5 days and 2.0 days to train SOLQ with R50 and R101 backbones, respectively. As for the Swin-Large backbone, it will take nearly four days to train due to the large computation cost.

Excuse me, do you use 2 GPUs or 8 GPUs for training for 1.5 days?  the read me you provided uses 8 GPUs. so I confused
