### ISSUE TITLE
How should SOLQ be extended to panoptic segmentation?

### ISSUE THREAD

**Issue by encounter1997** [megvii-research/SOLQ#6]
Hi authors, 

Thanks for the excellent work! I wish to extend SOLQ to panoptic segmentation. Shall I simply treat stuff and thing equally?
Looking forward to your suggestions!

**Comment by vaesl** [comment]
> Hi authors,
> 
> Thanks for the excellent work! I wish to extend SOLQ to panoptic segmentation. Shall I simply treat stuff and thing equally?
> Looking forward to your suggestions!

Hi, thanks for your interest on our work! SOLQ mainly focuses on the unified query representation of instances and object instances usually cover limited image areas. For panoptic segmentation task, the difficulty is how to deal with the stuff, which may cover very large image area sometimes and mix with the thing. So it is relatively hard to encode the stuff into fixed-dimention query vectors. Maybe you can combine our SOLQ with the recently introduced MaskFormer (https://arxiv.org/abs/2107.06278). Feel free to have a try!

**Comment by encounter1997** [comment]
Thanks for your kind reply and valuable suggestions!
