### ISSUE TITLE
ImportError: cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc'

### ISSUE THREAD

**Issue by sagnik1511** [megvii-research/SOLQ#7]
## ImportError

1. Git clone the repository of [SOLQ](https://github.com/megvii-research/SOLQ)
2. Update the dataset you want to use.
3. Update the data paths in the file SOLQ/datasets/coco.py
4.  RUn the bash file **configs/r50_solq_train.sh**

## Expected behavior

It should now show the error and move further to run the SOL-Q model.

## Environment

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.11 (default, Jul  3 2021, 18:01:19)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu102
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cu102
[conda] Could not collect

## Additional context

When running the script  ```!bash configs/r50_solq_train.sh``` it, shows ImportError like shown below :
``` 
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    import datasets
  File "/content/SOLQ/datasets/__init__.py", line 13, in <module>
    from .coco import build as build_coco
  File "/content/SOLQ/datasets/coco.py", line 23, in <module>
    from util.misc import get_local_rank, get_local_size
  File "/content/SOLQ/util/misc.py", line 36, in <module>
    from torchvision.ops.misc import _NewEmptyTensorOp
```

**Comment by dbofseuofhust** [comment]
> ## Error
> ## ImportError
> Steps to reproduce the behavior:
> 
> 1. Git clone the repository of [SOLQ](https://github.com/megvii-research/SOLQ)
> 2. Update the dataset you want to use.
> 3. Update the data paths in the file SOLQ/datasets/coco.py
> 4. RUn the bash file **configs/r50_solq_train.sh**
> 
> ## Expected behavior
> It should now show the error and move further to run the SOL-Q model.
> 
> ## Environment
> PyTorch version: 1.9.0+cu102
> Is debug build: False
> CUDA used to build PyTorch: 10.2
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 18.04.5 LTS (x86_64)
> GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
> CMake version: version 3.12.0
> Libc version: glibc-2.26
> 
> Python version: 3.7.11 (default, Jul 3 2021, 18:01:19) [GCC 7.5.0] (64-bit runtime)
> Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
> Is CUDA available: True
> CUDA runtime version: 11.0.221
> GPU models and configuration: GPU 0: Tesla T4
> Nvidia driver version: 460.32.03
> cuDNN version: Probably one of the following:
> /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
> /usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
> /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
> /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
> /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
> /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
> /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
> /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.19.5
> [pip3] torch==1.9.0+cu102
> [pip3] torchsummary==1.5.1
> [pip3] torchtext==0.10.0
> [pip3] torchvision==0.10.0+cu102
> [conda] Could not collect
> 
> ## Additional context
> When running the script `!bash configs/r50_solq_train.sh` it, shows ImportError like shown below :
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 22, in <module>
>     import datasets
>   File "/content/SOLQ/datasets/__init__.py", line 13, in <module>
>     from .coco import build as build_coco
>   File "/content/SOLQ/datasets/coco.py", line 23, in <module>
>     from util.misc import get_local_rank, get_local_size
>   File "/content/SOLQ/util/misc.py", line 36, in <module>
>     from torchvision.ops.misc import _NewEmptyTensorOp
> ```

Thanks for attention!
We used torch==1.7.0 and torchvision==0.8.1
The error is caused by torchvision version in this line https://github.com/megvii-research/SOLQ/blob/main/util/misc.py#L34.
Since your version is 0.10.0, so 'float(torchvision.__version__[:3]) < 0.5' is triggered and in fact it shouldn't be triggered becuase 0.10 is higher than 0.5. One solution is to change torchvision compatible rule to adjust 0.10.0 like this:

'float(torchvision.__version__.split('.')[1]) < 5' in line 30
'float(torchvision.__version__.split('.')[1]) < 7' in line 57
'float(torchvision.__version__.split('.')[1]) < 7' in line 507
'float(torchvision.__version__.split('.')[1]) < 5' in line 515

**Comment by sagnik1511** [comment]
Thanks, for the help. I was thinking to use `torch.empty()` , will that help in this case?
