### ISSUE TITLE
Add mask to the matching cost

### ISSUE THREAD

**Issue by zhanggang001** [megvii-research/SOLQ#8]
Hi, authors, have you tried computing the matching cost considering cls, reg, and mask together ?  Is there any difference in the performance? Thanks in advance.

**Comment by vaesl** [comment]
> Hi, authors, have you tried computing the matching cost considering cls, reg, and mask together ? Is there any difference in the performance? Thanks in advance.

Thanks for your pointing out this problem. For results reported in the paper, the mask branch is not included in matching cost. We have conducted the experiments using the mask loss as part of bipartite matching and the results show inferior performance (-0.7%) than those ignoring mask loss in bipartite matching. Large loss jitter is observed during the initial training stage. The participation of mask loss may affect the global matching between the object queries and ground-truths. We also notice that mask loss is not included in bipartite matching in VisTR (https://arxiv.org/abs/2011.14503).

**Comment by zhanggang001** [comment]
Thanks for such a detailed reply!

**Comment by zhanggang001** [comment]
> > Hi, authors, have you tried computing the matching cost considering cls, reg, and mask together ? Is there any difference in the performance? Thanks in advance.
> 
> Thanks for your pointing out this problem. For results reported in the paper, the mask branch is not included in matching cost. We have conducted the experiments using the mask loss as part of bipartite matching and the results show inferior performance (-0.7%) than those ignoring mask loss in bipartite matching. Large loss jitter is observed during the initial training stage. The participation of mask loss may affect the global matching between the object queries and ground-truths. We also notice that mask loss is not included in bipartite matching in VisTR (https://arxiv.org/abs/2011.14503).

Thanks for such a detailed reply!
